### ISSUE TITLE
Information Share: Possible conflict with existing health systems 

### ISSUE THREAD

**Issue by LucianDavies** [michaeldera/openhealthproposal#4]
You might want to check if they are not using this (https://github.com/dhis2) anymore. I remember at some point they had data aggregations done from a certain level going up on this platform.  slightly different from what you are proposing but if you are gonna pitch something its best to know if you are already competing with something else. best of luck good people

https://www.dhis2.org/inaction

**Comment by michaeldera** [comment]
Thank you for this. Perhaps I would be a lot more effective contributing to that. At the time I created this I was actively communicating with the team at the Ministry and they wanted something in writing.

**Comment by LucianDavies** [comment]
Sending you something pa email... my email is tldkhati@gmail.com

**Comment by michaeldera** [comment]
Cool.
